export interface Project {
  id: number;
  description_ar: string;
  description_en: string;
  name_ar: string;
  name_en: string;
  overview_description: string;
  project_number: string;
  project_slug: string;
  purposes: { [key: string]: any };
  short_description_ar: string;
  short_description_en: string;
  delivery_date: string;
  meta_description_en: string;
  meta_description_ar: string;
  meta_keywords_en: string;
  meta_keywords_ar: string;
  address_ar: string;
  address_en: string;
  logo: string | null;
  featured_image: string | null;
  about_image: string | null;
  gallery_images: string[] | null;
  master_plan_images: string[] | null;
  title_en: string;
  title_ar: string;
  area: number;
  latitude: number;
  longitude: number;
  is_featured: boolean;
  is_published: boolean;
  view_ids: number[];
  facility_ids: number[];
  amenity_ids: number[];
  purpose_id: number[];
  purpose_type_id: number[];
  video_iframe: string;
}

export class ProjectModel {
  id?: number | null;
  project_number: string | null;
  project_slug: string | null;
  description_en: string | null;
  description_ar: string | null;
  short_description_ar: string | null;
  short_description_en: string | null;
  delivery_date: string | null;
  meta_description_en: string | null;
  meta_description_ar: string | null;
  meta_keywords_en: string | null;
  meta_keywords_ar: string | null;
  logo: File | null;
  featured_image: File | null;
  about_image: File | null;
  gallery_images: File[] | null;
  master_plan_images: File[] | null;
  area: number | null;
  address_ar: string | null;
  address_en: string | null;
  title_en: string | null;
  title_ar: string | null;
  overview_description_en: string | null;
  overview_description_ar: string | null;
  latitude: number | null;
  longitude: number | null;
  video_iframe: string | null;
  is_featured: number;
  is_published: number;
  view_ids: number[] | [];
  facility_ids: number[] | [];
  service_ids: number[] | [];
  amenity_ids: number[] | [];
  unit_type_ids?: number[];
  purpose_id: number | null;
  purpose_type_id: number | null;
  area_unit_id: number | null;
  country_id: number | null;
  region_id: number | null;
  city_id: number | null;
  area_place_id: number | null;
  map_image: File | null;

  constructor(editData?: ProjectModel) {
    this.id = editData?.id || null;
    this.video_iframe = editData?.video_iframe || null;
    this.project_number = editData?.project_number || null;
    this.project_slug = editData?.project_slug || null;
    this.description_ar = editData?.description_ar || null;
    this.description_en = editData?.description_en || null;
    this.short_description_ar = editData?.short_description_ar || null;
    this.short_description_en = editData?.short_description_en || null;
    this.overview_description_en = editData?.overview_description_en || null;
    this.overview_description_ar = editData?.overview_description_ar || null;
    this.featured_image = editData?.featured_image || null;
    this.logo = editData?.logo || null;
    this.about_image = editData?.about_image || null;
    this.gallery_images = editData?.gallery_images || null;
    this.master_plan_images = editData?.master_plan_images || null;
    this.unit_type_ids = editData?.unit_type_ids || [];
    this.area = editData?.area || null;
    this.area_unit_id = editData?.area_unit_id || null;
    this.delivery_date = editData?.delivery_date || null;
    this.meta_description_en = editData?.meta_description_en || null;
    this.meta_description_ar = editData?.meta_description_ar || null;
    this.meta_keywords_en = editData?.meta_keywords_en || null;
    this.meta_keywords_ar = editData?.meta_keywords_ar || null;
    this.address_ar = editData?.address_ar || null;
    this.address_en = editData?.address_en || null;
    this.title_en = editData?.title_en || null;
    this.title_ar = editData?.title_ar || null;
    this.latitude = editData?.latitude || null;
    this.longitude = editData?.longitude || null;
    this.is_featured = editData?.is_featured || 0;
    this.is_published = editData?.is_published || 0;
    this.view_ids = editData?.view_ids || [];
    this.service_ids = editData?.service_ids || [];
    this.facility_ids = editData?.facility_ids || [];
    this.amenity_ids = editData?.amenity_ids || [];
    this.purpose_id = editData?.purpose_id || null;
    this.purpose_type_id = editData?.purpose_type_id || null;
    this.country_id = editData?.country_id || null;
    this.region_id = editData?.region_id || null;
    this.city_id = editData?.city_id || null;
    this.area_place_id = editData?.area_place_id || null;
    this.map_image = editData?.map_image || null;
  }
}
